swipe:
  3: 
    left: 
      command: 'bspc desktop -f next.occupied.local'
    right: 
      command: 'bspc desktop -f prev.occupied.local'

pinch:
  in:
    shortcut: 'ctrl+plus'
  out:
    shortcut: 'ctrl+minus'

threshold:
  swipe: 0.5
  pinch: 0.2

interval:
  swipe: 0.4
  pinch: 0.2