#! /bin/sh

sxhkd &

$HOME/.config/wpg/wp_init.sh &

# mouse cursor
xsetroot -cursor_name left_ptr &

# AUTOSTART
xinput --set-prop "12" "libinput Accel Speed" 0.5 #set trackpoint speed

$HOME/.config/polybar/launch.sh
dunst &

pkill compton
compton -f &

pgrep redshift-gtk || redshift-gtk -l 48.20849:16.37208 & # vienna hardcoded for now
pgrep lxsession || lxsession &
pgrep pasystray || pasystray &
pgrep xfce4-power-manager || xfce4-power-manager &
pgrep browserx || station & 

flameshot &


# BSPWM CONFIG

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DP1 -d 1 2 3 4 5 6 7 8 9 10

bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a code desktop='^10'
bspc rule -a code-oss desktop='^10'
bspc rule -a Station desktop='^8'
bspc rule -a Spotify desktop='^7'
bspc rule -a keepassxc desktop='^9'

bspc rule -a Pamac-manager state=floating
bspc rule -a Pamac-updater state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bash /home/matze/.config/bspwm/bspwm_colors.sh &bash /home/matze/.config/bspwm/bspwm_colors.sh &