[terminal]
vt = 2

# Auto-login on boot only
[initial_session]
command = "tuigreet --cmd Hyprland"
user = "matze"

# After logout: show the login screen instead of auto-logging in again
[default_session]
command = "tuigreet --cmd Hyprland"
user = "greeter"
