# Blackforest (VS Code:) dark terminal palette
# Hard-coded to match the current VS Code: theme and be darker than the OLED pywal scheme.
foreground         #d3c6aa
background         #000000
background_opacity 0.95
cursor             #d3c6aa

active_tab_foreground     #000000
active_tab_background     #d3c6aa
inactive_tab_foreground   #d3c6aa
inactive_tab_background   #000000

active_border_color   #d3c6aa
inactive_border_color #000000
bell_border_color     #e67e80

color0       #2e383c
color8       #859289
color1       #e67e80
color9       #e67e80
color2       #a7c080
color10      #a7c080
color3       #dbbc7f
color11      #dbbc7f
color4       #7fbbb3
color12      #7fbbb3
color5       #d699b6
color13      #d699b6
color6       #83c092
color14      #83c092
color7       #d3c6aa
color15      #d3c6aa