#! /bin/sh
urxvt &

pgrep sxhkd || mkdir -p $HOME/.logs && sxhkd >> $HOME/.logs/sxhkd 2>&1 &

$HOME/.config/wpg/wp_init.sh &

# mouse cursor
xsetroot -cursor_name left_ptr &

# AUTOSTART
xinput --set-prop "12" "libinput Accel Speed" 0.5 #set trackpoint speed

$HOME/.config/polybar/launch.sh
pgrep dunst || dunst &

pgrep picom || picom --experimental-backends &

pgrep redshift-gtk || redshift-gtk -l 48.20849:16.37208 & # vienna hardcoded for now
pgrep lxsession || lxsession &
pgrep pasystray || pasystray &
pgrep xfce4-power-manager || xfce4-power-manager &
pgrep browserx || station & 

flameshot &


# BSPWM CONFIG

${HOME}/.config/bspwm/workspaces_multimonitor &

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a code desktop='^10'
bspc rule -a code-oss desktop='^10'
bspc rule -a Station desktop='^8'
bspc rule -a Spotify desktop='^7'
bspc rule -a keepassxc desktop='^9'

bspc rule -a Pamac-manager state=floating center=on
bspc rule -a Pamac-updater state=floating center=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
