#! /bin/sh


# java UI fix
wmname LG3D


$HOME/.config/wpg/wp_init.sh &
xrdb ~/.Xresources

# proper mouse cursor
xsetroot -cursor_name left_ptr &

# set trackpoint speed
xinput --set-prop "12" "libinput Accel Speed" 0.5


# lock on suspend
pgrep xss-lock || xss-lock --transfer-sleep-lock -- lock --nofork &

# key-bindings
pgrep sxhkd || sxhkd -m -1 &
# FOR Debug: Not Prod!
# pgrep sxhkd || mkdir -p $HOME/.logs && sxhkd -m -1 >> $HOME/.logs/sxhkd 2>&1 &

# compositor
pgrep picom || picom --experimental-backends &


# BSPWM CONFIG

# fix for broken occupied empty tiles [not working]
# ${HOME}/.config/bspwm/kill_empty_nodes.sh &

${HOME}/.config/bspwm/workspaces_multimonitor &

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_motion_interval 5
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

bspc config border_width         4
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config directional_focus_tightness low

bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a code desktop='^10'
bspc rule -a code-oss desktop='^10'
bspc rule -a Spotify desktop='^7'
bspc rule -a keepassxc desktop='^9'

bspc rule -a Pamac-manager state=floating center=on
bspc rule -a Pamac-updater state=floating center=on
bspc rule -a Lua5.1 state=floating # gifine

# AUTOSTART
pgrep lxsession || lxsession &


$HOME/.config/polybar/launch.sh
pgrep dunst || dunst &

pgrep redshift-gtk || redshift-gtk -l 48.20849:16.37208 & # vienna hardcoded for now
# pgrep pasystray || pasystray & # why are there two instances (maybe lxsession)

pgrep flameshot || flameshot &
bash /home/matze/.config/bspwm/bspwm_colors.sh &


