#!/bin/bash

PIP_WIDTH=$((320*2))
PIP_HEIGHT=$((180*2))
MARGIN=50

bspc node -t floating -g sticky=on


DIMENSIONS=$(xdpyinfo | grep dimensions: | awk '{print $2}')
SCREEN_WIDTH=$(echo $DIMENSIONS | sed -r 's/x.*//')
SCREEN_HEIGHT=$(echo $DIMENSIONS | sed -r 's/.*x//')

PIP_X=$(($SCREEN_WIDTH - $PIP_WIDTH - $MARGIN))
PIP_Y=$(($SCREEN_HEIGHT - $PIP_HEIGHT - $MARGIN))

xdo resize -w $PIP_WIDTH -h $PIP_HEIGHT
xdo move -x $PIP_X -y $PIP_Y