windowrule = float, class:^(keepassxc)$
windowrule = float, title:^(File Operation Progress)$
windowrule = move 100%-600 100%-400, class:^(keepassxc)$
windowrule = move 83% 50%, class:^(Authy)$
windowrule = float, class:^(pavucontrol)$
windowrule = float, class:^(blueman-manager)$
windowrule = float, class:^(org.kde.polkit-kde-authentication-agent-1)$

windowrule = animation slide, class:^(rofi)$
windowrule = noanim, class:^(Wlogout)$

windowrule = float, class:^(rofi)$
windowrule = stayfocused, class:^(rofi)$
layerrule = blur, rofi
layerrule = blur, waybar
layerrule = blur, notifications

windowrule = float, title:^(Enter name of file to save to…)$
windowrule = size 720 380, title:^(Enter name of file to save to…)$

# Assistant window rules
windowrule = float, class:^(assistant)$
windowrule = size 80% 70%, class:^(assistant)$
windowrule = move 10% 25%, class:^(assistant)$
windowrule = workspace special:assistant silent, class:^(assistant)$
windowrule = suppressevent fullscreen, class:^(assistant)$

windowrule = float, title:^(Picture-in-Picture)$
windowrule = size 640 360, title:^(Picture-in-Picture)$
windowrule = move 100%-680 100%-400, title:^(Picture-in-Picture)$
windowrule = pin, title:^(Picture-in-Picture)$

windowrule = idleinhibit fullscreen, class:^(*)$
windowrule = idleinhibit fullscreen, title:^(*)$
windowrule = idleinhibit fullscreen, fullscreen:1