#!/bin/bash

NODE_WIDTH=$((320*3))
NODE_HEIGHT=$((180*3))
MARGIN=50

bspc node focused -t floating -g sticky=on
bspc node -f

DIMENSIONS=$(xdpyinfo | grep dimensions: | awk '{print $2}')
SCREEN_WIDTH=$(echo $DIMENSIONS | sed -r 's/x.*//')
SCREEN_HEIGHT=$(echo $DIMENSIONS | sed -r 's/.*x//')

NODE_X=$(($SCREEN_WIDTH - $NODE_WIDTH - $MARGIN))
NODE_Y=$(($SCREEN_HEIGHT - $NODE_HEIGHT - $MARGIN))

xdotool getactivewindow windowsize $NODE_WIDTH $NODE_HEIGHT windowmove $NODE_X $NODE_Y