#!/bin/bash
. "${HOME}/.cache/wal/colors.sh"

BLANK='#00000000'
CLEAR='#ffffff22'
DEFAULT="${color6}ee"
VERIFYING="${color3}ee"
TYPING="${color5}ee"
WRONG="${color1}ee"


# suspend message display
# source: https://faq.i3wm.org/question/5654/how-can-i-disable-notifications-when-the-screen-locks-and-enable-them-again-when-unlocking/
pkill -u "$USER" -USR1 dunst


# lock the screen
#
i3lock-fancy-rapid 5 3 -n \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
--keyhl=$TYPING          \
--verif-text="" --wrong-text=""


# resume message display
pkill -u "$USER" -USR2 dunst