#!/usr/bin/bash

# src: https://github.com/knadh/rofi-vscode-projects

TITLE='vscode-project'

LAUNCHER='rofi -dmenu -p'
#LAUNCHER='dmenu -p'
#LAUNCHER='dmenu-mac -p'
#LAUNCHER='choose'

# Path to the projects.json file (vscode alefragnani project manager)
# SRC=~/.config/Code\ -\ OSS/User/globalStorage/alefragnani.project-manager/projects.json
SRC=~/.config/Code/User/globalStorage/alefragnani.project-manager/projects.json

prj=$(jq -r "sort_by(.name) | .[].name" < "$SRC" | $LAUNCHER $TITLE $@)


# If there was a selection, find its path from the src file and launch vscode.
if [ -n "$prj" ]; then
    prjpath=$(jq -r --arg prj "$prj" '.[] | select(.name==$prj) | .rootPath' < "$SRC")
    code $prjpath
fi